# This is a basic workflow to help you get started with Actions

name: work-flow

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'world'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Send Greeting
        run: echo "Hello ${{ github.event.inputs.name }}"

